// Speaker script for the talk "Weight Without Width": one entry per slide, shared by the deck (presenter notes), the transcript page and the recording kit.

/** One slide's script: its deck id, a human label, and the spoken text with [bracketed] cues for builds and cuts. */
export interface ScriptEntry {
	id: string
	label: string
	text: string
}

/** The script in slide order. Use typographic apostrophes (’) only: a straight one breaks this file. */
export const SCRIPT: ScriptEntry[] = [
	{ id: 'cover', label: 'Weight Without Width', text: 'Watch the top row. Each word gets bolder in turn, and everything after it shuffles along. Now the bottom row. Same words, just as bold, and nothing moves. That difference is what I’ve been chasing.' },
	{ id: 'hook', label: 'The problem', text: 'You’ve seen this a thousand times. You hover a menu item, it goes bold, and the whole menu twitches. Nav bars, tabs, those little filter chips: anywhere bold means you’re here. [Next] Bold letters are wider than regular ones, so the word grows, and the rest of the line moves over to make room.' },
	{ id: 'history', label: 'Asked in 2009', text: 'People have been asking about this for a long time. In February 2009 someone posted it on Stack Overflow: inline elements shifting when made bold on hover. [Next] The first answer, the same morning, said there was no way to avoid it, except by compromises like fixed widths. [Next] That question has had about a quarter of a million views. And by the end of 2009 people were already patching it with JavaScript.' },
	{ id: 'hacks', label: 'The workarounds', text: 'So we built workarounds. [Next] The best one is pure CSS: you hide a bold copy of the label behind the real one, so the box is already wide enough. For a nav bar, honestly, it works well. Microsoft and GitHub both ship it in their tab components, with comments in the code saying why. The cost is empty space around every label at rest. [Next] Some people fake the boldness with a text shadow or a stroke, which never quite looks like bold. [Next] And some just guess a negative letter-spacing, which holds for one font at one size.' },
	{ id: 'measure', label: 'How much it moves', text: 'I wanted a number. We took fifteen of the most popular variable fonts on Google Fonts, set six navigation labels and a sentence at sixteen pixels with HarfBuzz, which is the shaping engine Chrome and Firefox use, and compared weight 400 with 700. [Next] On median, the labels got 4.8 percent wider. The worst was over nine.' },
	{ id: 'families', label: 'Font by font', text: 'And it really depends on the typeface. [Next] Work Sans and Roboto barely move, about one percent, so picking a font like that is a perfectly good fix on its own. [Next] Inter and Montserrat sit around five. [Next] Open Sans and Rubik grow nearly eight percent. That’s two to nine pixels per label.' },
	{ id: 'grade', label: 'Grade', text: 'Type designers dealt with this a long time ago. [Next] There’s an axis called grade. It changes how thick the strokes are without changing how wide the letters are. Google’s glossary says it was originally conceived for printed newspapers, to calibrate output from different presses. [Next] We checked it in Roboto Flex. Across the whole grade range, the width of our labels changed by zero.' },
	{ id: 'census', label: 'Who ships grade', text: 'So which fonts have it? I went through the whole Google Fonts catalogue. [Next] Of five hundred and forty-four variable families with a weight axis, five have grade. Five. But ninety-six have a width axis, and that turns out to matter.' },
	{ id: 'compare', label: 'What it looks like', text: 'Here’s the same word, blown up four times, in Roboto Flex. The red line is where Regular ends. Plain bold runs past it. Bold with tightened letter-spacing, which is what our library does, holds the line, but look at the t and the i: it’s tight. Bold that’s narrowed with the width axis holds the line and keeps its spacing. And grade holds the line and looks the most natural of all.' },
	{ id: 'order', label: 'The order', text: 'So if you remember one thing: reach for grade first. If the font doesn’t have it, narrow it with the width axis. And if it has neither, tighten the spacing, by exactly the amount you measured.' },
	{ id: 'how', label: 'How hoverBoldly works', text: 'That last case is why we built hoverBoldly. It’s ours, and it’s free. And it isn’t a new idea: in 2013 the type designer Hrant Papazian called it fixed-offset, two weights made the same width by a set amount of tracking. [Next] It measures the text at both weights in a canvas, off the page. [Next] It divides the extra width by the number of characters. [Next] It tightens the letter-spacing by that much, on top of any spacing you already set. [Next] And it bumps the weight at the same moment. [Next] It’s built for text in a paragraph, where you can’t reserve space the way the CSS trick does.' },
	{ id: 'holds', label: 'Does it hold?', text: 'We tested it in Chrome, on the shipped code. [Next] Mixed-case labels: plain bold moved a median of three and a half pixels. With hoverBoldly, zero, and at most two hundredths of a pixel. [Next] Tracked uppercase labels were the interesting one. Our old version made them worse, up to twenty-three pixels, because it threw away your letter-spacing. The fixed version holds them to under a fifth of a pixel. And sweeping a pointer across a menu, Chrome logged four to eight layout shifts with plain bold, and none with ours.' },
	{ id: 'demo', label: 'Demo', text: 'Here it is on the site. [Cut to demo: sweep across the paragraph on hoverboldly.com.] Every word you hover goes bold, and the paragraph doesn’t reflow.' },
	{ id: 'limits', label: 'Where it falls short', text: 'A few things it doesn’t do. It needs a variable font with a weight axis. Tightened bold is visibly tighter than real bold, so if your font has grade or width, use those. Keyboard focus works in the default mode, and you should still keep a focus ring. And for a nav bar, the CSS copy trick is often the simpler choice.' },
	{ id: 'ask', label: 'Three asks', text: 'Three asks. [Next] Type designers: ship a grade axis, or at least a width axis, in your web families. [Next] Designers and developers: let the weight change and leave the width alone; grade first, width second, spacing last. [Next] And the CSS working group: there are two open issues right now, one on synthetic bold and one on a bold-text preference, and the minutes already mention grade. I’d love to see them grow into a way to ask for emphasis without movement.' },
	{ id: 'close', label: 'Close', text: 'Weight changes emphasis. Width changes layout. Thanks for watching. Everything’s at hoverboldly.com.' },
	{ id: 'about', label: 'Who we are', text: 'We’re Overpunch. We’ve built websites for type foundries for over fifteen years, and we’re building Typetin, a storefront for independent foundries, with a waitlist at typetin.com. hoverBoldly is one of twenty type tools we make for the web.' },
]

/** Script text keyed by slide id, for the deck's presenter notes. */
export const SCRIPT_NOTES: Record<string, string> = Object.fromEntries(SCRIPT.map(e => [e.id, e.text]))

/** Strips [bracketed] build and cut cues, leaving only the spoken words. */
export function spoken(text: string): string {
	return text.replace(/\s*\[[^\]]*\]\s*/g, ' ').replace(/\s+/g, ' ').trim()
}
